/// Flutter icons FaceIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FaceIcon
///      fonts:
///       - asset: fonts/FaceIcon.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class FaceIcon {
  FaceIcon._();

  static const _kFontFam = 'FaceIcon';

  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
}
